import express from 'express';

type Luminaire = { id: number; code: string; street: string; lat: number; lon: number; lampType: 'SODIUM' | 'LED' | 'METAL_HALIDE'; wattage: number; installedAt: string; status: 'active' | 'warning' | 'fault' | 'inactive'; zoneId: number };
const users = { ADMIN: ['admin@lumen.local', 'ADMIN'], COUNCIL: ['council@lumen.local', 'COUNCIL'], CONTRACTOR: ['contractor@lumen.local', 'CONTRACTOR'], VIEWER: ['viewer@lumen.local', 'VIEWER'] } as const;
const lamps: Luminaire[] = Array.from({ length: 600 }, (_, index) => ({ id: index + 1, code: `LUM-${String(index + 1).padStart(4, '0')}`, street: `${['Harbour', 'North', 'Market', 'Cedar'][index % 4]} Street`, lat: 64.14 + (index % 25) * .002, lon: -21.94 + (index % 19) * .002, lampType: ['SODIUM', 'LED', 'METAL_HALIDE'][index % 3] as Luminaire['lampType'], wattage: [70, 100, 150][index % 3], installedAt: `202${index % 5}-0${(index % 9) + 1}-15`, status: ['active', 'warning', 'fault', 'inactive'][index % 4] as Luminaire['status'], zoneId: (index % 12) + 1 }));
const token = (role: keyof typeof users) => `eyJhbGciOiJub25lIn0.${Buffer.from(JSON.stringify({ sub: users[role][0], roles: [role], exp: Math.floor(Date.now() / 1000) + 3600 })).toString('base64url')}.`;
const app = express(); app.use(express.json());
const delay = () => new Promise((resolve) => setTimeout(resolve, 300 + Math.random() * 600));

app.post('/api/auth/login', (request, response) => { const role = (request.body?.role ?? 'VIEWER') as keyof typeof users; if (!(role in users)) return response.status(401).json({ message: 'Unknown training role' }); return response.json({ token: token(role) }); });
app.get('/api/luminaires/paged', async (request, response) => { await delay(); const page = Math.max(1, Number(request.query.page ?? 1)); const perPage = Math.min(100, Math.max(1, Number(request.query.perPage ?? 20))); const search = String(request.query.searchTerm ?? '').toLowerCase(); const sort = String(request.query.sort ?? 'code'); const direction = request.query.direction === 'DESC' ? -1 : 1; const filtered = lamps.filter((lamp) => `${lamp.code} ${lamp.street}`.toLowerCase().includes(search)).sort((a, b) => String(a[sort as keyof Luminaire] ?? '').localeCompare(String(b[sort as keyof Luminaire] ?? '')) * direction); const lastPage = Math.max(1, Math.ceil(filtered.length / perPage)); response.json({ data: filtered.slice((page - 1) * perPage, page * perPage), currentPage: page, lastPage, total: filtered.length, perPage }); });
app.get('/api/luminaires/:id/energy', (request, response) => { const start = new Date(String(request.query.from ?? Date.now() - 24 * 3600_000)); response.json(Array.from({ length: 24 }, (_, hour) => ({ at: new Date(start.getTime() + hour * 3600_000).toISOString(), kwh: Number((2.5 + Math.sin(hour / 24 * Math.PI * 2) + (Number(request.params.id) % 7) / 10).toFixed(2)) }))); });
app.get('/api/traps/500', (_request, response) => response.status(500).json({ message: 'Deliberate exercise error' }));
app.get('/api/traps/slow', async (_request, response) => { await new Promise((resolve) => setTimeout(resolve, 4000)); response.json({ ok: true }); });
app.listen(3000, () => console.log('Mock API listening on http://localhost:3000'));
